services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: anamasflavia/sprint-2-pb-rg-pel
    container_name: sprint-2-pb-rg-pel
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - prod

  mongodb:
    image: mongo
    container_name: db
    ports: 
      - 27017:27017
    networks:
      - prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: personagem

networks: 
    prod:
        driver: bridge